### ISSUE TITLE
A minor nit...

### ISSUE THREAD

**Issue by cclauss** [dhruvmanila/algobot#2]
```yaml
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
        if: ${{ success() }}
```
Is this backwards?  If success then run... -- I know that it runs either way but I find it a bit confusing.
